// Identifier utilities. Two flavors of id are used in the app:
//
//   ULID  — 26 Crockford-base32 chars, sortable by creation time. Used
//           for the internal database primary key (items.id, activity
//           logs reference). Generated by `generateUlid()`.
//
//   ShortID — 8 Crockford-base32 chars formatted as `XXXX-XXXX`. Used
//             for the human-facing tag printed on the QR sticker
//             (items.qrCode). Easy to read, type, or eyeball.

const CROCKFORD = "0123456789ABCDEFGHJKMNPQRSTVWXYZ"
const SHORT_ID_ALPHABET = CROCKFORD
const SHORT_ID_GROUP_LEN = 4
const SHORT_ID_GROUP_COUNT = 2

const ULID_TIME_LEN = 10
const ULID_RANDOM_LEN = 16
const ULID_REGEX = /^[0-9A-HJKMNP-TV-Z]{26}$/

function randomBytes(length: number): Uint8Array {
  const buf = new Uint8Array(length)
  if (
    typeof globalThis.crypto !== "undefined" &&
    typeof globalThis.crypto.getRandomValues === "function"
  ) {
    globalThis.crypto.getRandomValues(buf)
    return buf
  }
  for (let i = 0; i < length; i++) {
    buf[i] = Math.floor(Math.random() * 256)
  }
  return buf
}

function encodeBase32(bytes: Uint8Array, length: number): string {
  // MSB-first base32 encoding over a Crockford alphabet.
  let out = ""
  let bits = 0
  let buffer = 0
  for (const byte of bytes) {
    buffer = (buffer << 8) | byte
    bits += 8
    while (bits >= 5) {
      bits -= 5
      const idx = (buffer >> bits) & 0x1f
      out += CROCKFORD[idx]
    }
  }
  if (out.length !== length) {
    throw new Error(
      `base32 encode: expected ${length} chars, got ${out.length}`
    )
  }
  return out
}

/**
 * Generate a short ID for the printable QR code.
 * Format: `XXXX-XXXX` (Crockford base32, no I/L/O/U).
 * Example: `X7R2-M9WP`
 */
export function generateShortId(): string {
  // 32 bits of entropy fit nicely in 4 base32 chars; two groups → 8 chars.
  const groups: string[] = []
  for (let i = 0; i < SHORT_ID_GROUP_COUNT; i++) {
    const bytes = randomBytes(4)
    groups.push(encodeBase32(bytes, SHORT_ID_GROUP_LEN))
  }
  return groups.join("-")
}

/**
 * The QR code printed on a furniture tag. Today this is the same shape as
 * `generateShortId()`. Kept as a separate function so future tweaks to
 * the printable tag (e.g. a brand prefix) don't bleed into the short id.
 */
export function generateQrCode(): string {
  return generateShortId()
}

export const SHORT_ID_REGEX = new RegExp(
  `^[${SHORT_ID_ALPHABET}]{${SHORT_ID_GROUP_LEN}}-[${SHORT_ID_ALPHABET}]{${SHORT_ID_GROUP_LEN}}$`
)

export function isShortId(value: unknown): value is string {
  return typeof value === "string" && SHORT_ID_REGEX.test(value)
}

/**
 * Generate a new ULID. Sortable by creation time, 26 Crockford base32 chars.
 * Example: `01H8XGJWBWBAQ4ZEXAMPLE00`
 */
export function generateUlid(now: Date = new Date()): string {
  const time = now.getTime()
  if (!Number.isFinite(time) || time < 0) {
    throw new Error("ULID: invalid timestamp")
  }
  const timeBytes = new Uint8Array(6)
  timeBytes[0] = (time / 2 ** 40) & 0xff
  timeBytes[1] = (time / 2 ** 32) & 0xff
  timeBytes[2] = (time / 2 ** 24) & 0xff
  timeBytes[3] = (time / 2 ** 16) & 0xff
  timeBytes[4] = (time / 2 ** 8) & 0xff
  timeBytes[5] = time & 0xff
  const timeEncoded = encodeBase32(timeBytes, ULID_TIME_LEN)
  const randomEncoded = encodeBase32(randomBytes(10), ULID_RANDOM_LEN)
  return timeEncoded + randomEncoded
}

export function isUlid(value: unknown): value is string {
  return typeof value === "string" && ULID_REGEX.test(value)
}

export function ulidTimestamp(ulid: string): Date | null {
  if (!isUlid(ulid)) return null
  const timeChars = ulid.slice(0, ULID_TIME_LEN)
  let value = 0
  for (const ch of timeChars) {
    const idx = CROCKFORD.indexOf(ch)
    if (idx < 0) return null
    value = (value << 5) | idx
  }
  return new Date(value)
}
