import {
  index,
  pgEnum,
  pgTable,
  text,
  timestamp,
  uuid,
} from "drizzle-orm/pg-core"

export const ITEM_STATUSES = [
  "Available",
  "In Storage",
  "Reserved",
  "Staged",
  "Repair",
  "Retired",
] as const

export const ITEM_CONDITIONS = ["Excellent", "Good", "Worn", "Repair"] as const

export type ItemStatus = (typeof ITEM_STATUSES)[number]
export type ItemCondition = (typeof ITEM_CONDITIONS)[number]

export const itemStatus = pgEnum("item_status", ITEM_STATUSES)
export const condition = pgEnum("condition", ITEM_CONDITIONS)

export const items = pgTable(
  "items",
  {
    // Sortable Crockford-base32 ULID generated by the app. Looks like
    // 01H8XGJWBWBAQ4ZEXAMPLE00 — easier to read & skim than a UUID v4.
    id: text("id").primaryKey(),
    qrCode: text("qr_code").notNull().unique(),
    name: text("name").notNull(),
    description: text("description").notNull().default(""),
    condition: condition("condition").notNull().default("Good"),
    location: text("location").notNull(),
    status: itemStatus("status").notNull().default("In Storage"),
    takenOutAt: timestamp("taken_out_at", { withTimezone: true }),
    imageUrl: text("image_url").notNull().default(""),
    createdBy: text("created_by").notNull().default(""),
    createdAt: timestamp("created_at", { withTimezone: true })
      .notNull()
      .defaultNow(),
    updatedAt: timestamp("updated_at", { withTimezone: true })
      .notNull()
      .defaultNow(),
  },
  (table) => [
    index("idx_items_qr_code").on(table.qrCode),
    index("idx_items_status").on(table.status),
    index("idx_items_name").on(table.name),
  ]
)

export const ACTIVITY_ACTIONS = [
  "created",
  "updated",
  "deleted",
  "checked_out",
  "checked_in",
  "reported_damaged",
  "moved",
  "condition_changed",
] as const

export type ActivityAction = (typeof ACTIVITY_ACTIONS)[number]

export const activityAction = pgEnum("activity_action", ACTIVITY_ACTIONS)

export const activityLogs = pgTable(
  "activity_logs",
  {
    id: uuid("id").primaryKey().defaultRandom(),
    // No FK so logs survive item deletion. Nullable for the same reason.
    // Stored as text to match items.id (ULID).
    itemId: text("item_id"),
    userId: text("user_id").notNull(),
    userName: text("user_name").notNull().default(""),
    userEmail: text("user_email").notNull().default(""),
    action: activityAction("action").notNull(),
    // Snapshot of the item at the time of the action — keeps the log useful
    // even if the item is later renamed, relocated, or removed.
    itemName: text("item_name").notNull().default(""),
    itemQrCode: text("item_qr_code").notNull().default(""),
    fromLocation: text("from_location"),
    toLocation: text("to_location"),
    fromCondition: condition("from_condition"),
    toCondition: condition("to_condition"),
    createdAt: timestamp("created_at", { withTimezone: true })
      .notNull()
      .defaultNow(),
  },
  (table) => [
    index("idx_activity_logs_item_id").on(table.itemId, table.createdAt),
    index("idx_activity_logs_created_at").on(table.createdAt),
    index("idx_activity_logs_user_id").on(table.userId, table.createdAt),
  ]
)
