import {
  boolean,
  index,
  integer,
  pgEnum,
  pgTable,
  primaryKey,
  text,
  timestamp,
  uniqueIndex,
  uuid,
} from "drizzle-orm/pg-core"
import {
  ITEM_STATUSES,
  ITEM_CONDITIONS,
  ITEM_KINDS,
  PRINT_SIZES,
  TAG_COLORS,
  ACTIVITY_ACTIONS,
} from "./constants"
import type {
  ItemStatus,
  ItemCondition,
  ItemKind,
  PrintSize,
  TagColor,
  ActivityAction,
} from "./constants"

export {
  ITEM_STATUSES,
  ITEM_CONDITIONS,
  ITEM_KINDS,
  PRINT_SIZES,
  TAG_COLORS,
  ACTIVITY_ACTIONS,
}
export type {
  ItemStatus,
  ItemCondition,
  ItemKind,
  PrintSize,
  TagColor,
  ActivityAction,
}

export const itemStatus = pgEnum("item_status", ITEM_STATUSES)
export const condition = pgEnum("condition", ITEM_CONDITIONS)

export const itemKind = pgEnum("item_kind", ITEM_KINDS)

export const printSize = pgEnum("print_size", PRINT_SIZES)

export const items = pgTable(
  "items",
  {
    // Sortable Crockford-base32 ULID generated by the app. Looks like
    // 01H8XGJWBWBAQ4ZEXAMPLE00 — easier to read & skim than a UUID v4.
    id: text("id").primaryKey(),
    orgId: text("org_id").notNull(),
    // unit = one physical item per row (current behavior).
    // bulk = fungible stock (pillows etc.); quantities live in item_batches
    // and this row's location/status/condition mirror the first batch.
    kind: itemKind("kind").notNull().default("unit"),
    qrCode: text("qr_code").notNull(),
    name: text("name").notNull(),
    description: text("description").notNull().default(""),
    condition: condition("condition").notNull().default("Good"),
    location: text("location").notNull(),
    status: itemStatus("status").notNull().default("In Storage"),
    takenOutAt: timestamp("taken_out_at", { withTimezone: true }),
    imageUrl: text("image_url").notNull().default(""),
    // R2 object key for the photo, scoped as `orgs/{orgId}/items/{itemId}/{ulid}.{ext}`.
    // Used by the server to read/delete the object. Never returned to the client.
    imageKey: text("image_key"),
    createdBy: text("created_by").notNull().default(""),
    // Clerk org role required to update/delete this item. Null = any org
    // member can edit. Currently only "org:admin" is selectable in the UI.
    requiredRole: text("required_role"),
    // QR label size for printing. Defaults to "medium". Only override for
    // unusually small (plants, jewelry) or large (paintings, rugs) items.
    printSize: printSize("print_size").notNull().default("medium"),
    // For bulk items: whether individual units wear physical QR tags.
    // True = tagged (every unit has its own QR), false = untagged (rack sheet only).
    tagged: boolean("tagged").notNull().default(true),
    categoryId: text("category_id"),
    createdAt: timestamp("created_at", { withTimezone: true })
      .notNull()
      .defaultNow(),
    updatedAt: timestamp("updated_at", { withTimezone: true })
      .notNull()
      .defaultNow(),
  },
  (table) => [
    uniqueIndex("items_org_qr_unique").on(table.orgId, table.qrCode),
    index("idx_items_org_id").on(table.orgId),
    index("idx_items_qr_code").on(table.qrCode),
    index("idx_items_status").on(table.status),
    index("idx_items_name").on(table.name),
    // Trigram GIN indexes power the `ILIKE '%…%'` search on name and QR
    // code. Requires the `pg_trgm` extension (created by the migration).
    index("idx_items_name_trgm").using("gin", table.name.op("gin_trgm_ops")),
    index("idx_items_qr_code_trgm").using(
      "gin",
      table.qrCode.op("gin_trgm_ops")
    ),
  ]
)

export const tags = pgTable(
  "tags",
  {
    id: text("id").primaryKey(),
    orgId: text("org_id").notNull(),
    name: text("name").notNull(),
    // Lowercase hex from TAG_COLORS.
    color: text("color").notNull().default("#6b7280"),
    createdAt: timestamp("created_at", { withTimezone: true })
      .notNull()
      .defaultNow(),
  },
  (table) => [
    uniqueIndex("tags_org_name_unique").on(table.orgId, table.name),
    index("idx_tags_org_id").on(table.orgId),
  ]
)

export const categories = pgTable(
  "categories",
  {
    id: text("id").primaryKey(),
    orgId: text("org_id").notNull(),
    name: text("name").notNull(),
    parentId: text("parent_id"),
  },
  (table) => [
    index("idx_categories_org_id").on(table.orgId),
    index("idx_categories_parent_id").on(table.parentId),
    uniqueIndex("categories_org_parent_name_unique").on(
      table.orgId,
      table.parentId,
      table.name
    ),
  ]
)

export const itemTags = pgTable(
  "item_tags",
  {
    // orgId denormalized onto the join row so every query stays org-scoped
    // without an extra join back through items.
    orgId: text("org_id").notNull(),
    itemId: text("item_id").notNull(),
    tagId: text("tag_id").notNull(),
  },
  (table) => [
    primaryKey({ columns: [table.itemId, table.tagId] }),
    index("idx_item_tags_org_id").on(table.orgId),
    index("idx_item_tags_tag_id").on(table.tagId),
  ]
)

/**
 * One batch of fungible (bulk) stock: `qty` units of an item in a single
 * location/status/condition. An item's total quantity is the sum of its
 * batches. Batches auto-delete when they reach qty 0.
 */
export const itemBatches = pgTable(
  "item_batches",
  {
    id: text("id").primaryKey(),
    orgId: text("org_id").notNull(),
    itemId: text("item_id").notNull(),
    qty: integer("qty").notNull(),
    location: text("location").notNull(),
    status: itemStatus("status").notNull().default("In Storage"),
    condition: condition("condition").notNull().default("Good"),
    createdAt: timestamp("created_at", { withTimezone: true })
      .notNull()
      .defaultNow(),
    updatedAt: timestamp("updated_at", { withTimezone: true })
      .notNull()
      .defaultNow(),
  },
  (table) => [
    index("idx_item_batches_org_id").on(table.orgId),
    index("idx_item_batches_item_id").on(table.itemId),
    index("idx_item_batches_location").on(table.location),
    index("idx_item_batches_status").on(table.status),
  ]
)

/**
 * A physical storage rack/bin with its own QR code. Holds a curated
 * collection of (usually untagged) bulk items with per-rack quantities.
 */
export const racks = pgTable(
  "racks",
  {
    id: text("id").primaryKey(),
    orgId: text("org_id").notNull(),
    name: text("name").notNull(),
    location: text("location").notNull().default(""),
    qrCode: text("qr_code").notNull(),
    createdAt: timestamp("created_at", { withTimezone: true })
      .notNull()
      .defaultNow(),
    updatedAt: timestamp("updated_at", { withTimezone: true })
      .notNull()
      .defaultNow(),
  },
  (table) => [
    uniqueIndex("racks_org_qr_unique").on(table.orgId, table.qrCode),
    index("idx_racks_org_id").on(table.orgId),
  ]
)

export const rackItems = pgTable(
  "rack_items",
  {
    rackId: text("rack_id").notNull(),
    orgId: text("org_id").notNull(),
    itemId: text("item_id").notNull(),
    qty: integer("qty").notNull().default(1),
  },
  (table) => [
    primaryKey({ columns: [table.rackId, table.itemId] }),
    index("idx_rack_items_org_id").on(table.orgId),
    index("idx_rack_items_rack_id").on(table.rackId),
    index("idx_rack_items_item_id").on(table.itemId),
  ]
)

export const activityAction = pgEnum("activity_action", ACTIVITY_ACTIONS)

export const activityLogs = pgTable(
  "activity_logs",
  {
    id: uuid("id").primaryKey().defaultRandom(),
    orgId: text("org_id").notNull(),
    // No FK so logs survive item deletion. Nullable for the same reason.
    // Stored as text to match items.id (ULID).
    itemId: text("item_id"),
    userId: text("user_id").notNull(),
    userName: text("user_name").notNull().default(""),
    userEmail: text("user_email").notNull().default(""),
    action: activityAction("action").notNull(),
    // Snapshot of the item at the time of the action — keeps the log useful
    // even if the item is later renamed, relocated, or removed.
    itemName: text("item_name").notNull().default(""),
    itemQrCode: text("item_qr_code").notNull().default(""),
    fromLocation: text("from_location"),
    toLocation: text("to_location"),
    fromCondition: condition("from_condition"),
    toCondition: condition("to_condition"),
    // Units affected — set for bulk (batch) actions, null for unit items.
    quantity: integer("quantity"),
    createdAt: timestamp("created_at", { withTimezone: true })
      .notNull()
      .defaultNow(),
  },
  (table) => [
    index("idx_activity_logs_org_id").on(table.orgId, table.createdAt),
    index("idx_activity_logs_item_id").on(table.itemId, table.createdAt),
    index("idx_activity_logs_created_at").on(table.createdAt),
    index("idx_activity_logs_user_id").on(table.userId, table.createdAt),
  ]
)
