import {
  index,
  integer,
  pgEnum,
  pgTable,
  primaryKey,
  text,
  timestamp,
  uniqueIndex,
  uuid,
} from "drizzle-orm/pg-core"

export const ITEM_STATUSES = [
  "Available",
  "In Storage",
  "Reserved",
  "Staged",
  "Repair",
  "Retired",
  "Pending Tag",
] as const

export const ITEM_CONDITIONS = ["Excellent", "Good", "Worn", "Repair"] as const

export type ItemStatus = (typeof ITEM_STATUSES)[number]
export type ItemCondition = (typeof ITEM_CONDITIONS)[number]

export const itemStatus = pgEnum("item_status", ITEM_STATUSES)
export const condition = pgEnum("condition", ITEM_CONDITIONS)

export const ITEM_KINDS = ["unit", "bulk"] as const
export type ItemKind = (typeof ITEM_KINDS)[number]
export const itemKind = pgEnum("item_kind", ITEM_KINDS)

export const PRINT_SIZES = ["small", "medium", "large"] as const
export type PrintSize = (typeof PRINT_SIZES)[number]
export const printSize = pgEnum("print_size", PRINT_SIZES)

export const items = pgTable(
  "items",
  {
    // Sortable Crockford-base32 ULID generated by the app. Looks like
    // 01H8XGJWBWBAQ4ZEXAMPLE00 — easier to read & skim than a UUID v4.
    id: text("id").primaryKey(),
    orgId: text("org_id").notNull(),
    // unit = one physical item per row (current behavior).
    // bulk = fungible stock (pillows etc.); quantities live in item_batches
    // and this row's location/status/condition mirror the first batch.
    kind: itemKind("kind").notNull().default("unit"),
    qrCode: text("qr_code").notNull(),
    name: text("name").notNull(),
    description: text("description").notNull().default(""),
    condition: condition("condition").notNull().default("Good"),
    location: text("location").notNull(),
    status: itemStatus("status").notNull().default("In Storage"),
    takenOutAt: timestamp("taken_out_at", { withTimezone: true }),
    imageUrl: text("image_url").notNull().default(""),
    // R2 object key for the photo, scoped as `orgs/{orgId}/items/{itemId}/{ulid}.{ext}`.
    // Used by the server to read/delete the object. Never returned to the client.
    imageKey: text("image_key"),
    createdBy: text("created_by").notNull().default(""),
    // Clerk org role required to update/delete this item. Null = any org
    // member can edit. Currently only "org:admin" is selectable in the UI.
    requiredRole: text("required_role"),
    // QR label size for printing. Defaults to "medium". Only override for
    // unusually small (plants, jewelry) or large (paintings, rugs) items.
    printSize: printSize("print_size").notNull().default("medium"),
    createdAt: timestamp("created_at", { withTimezone: true })
      .notNull()
      .defaultNow(),
    updatedAt: timestamp("updated_at", { withTimezone: true })
      .notNull()
      .defaultNow(),
  },
  (table) => [
    uniqueIndex("items_org_qr_unique").on(table.orgId, table.qrCode),
    index("idx_items_org_id").on(table.orgId),
    index("idx_items_qr_code").on(table.qrCode),
    index("idx_items_status").on(table.status),
    index("idx_items_name").on(table.name),
  ]
)

/**
 * Preset tag colors. Stored as lowercase hex on the tag row; the UI offers
 * this palette only, so colors stay consistent across the app.
 */
export const TAG_COLORS = [
  { name: "Red", value: "#ef4444" },
  { name: "Orange", value: "#f97316" },
  { name: "Amber", value: "#f59e0b" },
  { name: "Green", value: "#22c55e" },
  { name: "Teal", value: "#14b8a6" },
  { name: "Blue", value: "#3b82f6" },
  { name: "Purple", value: "#a855f7" },
  { name: "Pink", value: "#ec4899" },
  { name: "Gray", value: "#6b7280" },
] as const

export type TagColor = (typeof TAG_COLORS)[number]["value"]

export const tags = pgTable(
  "tags",
  {
    id: text("id").primaryKey(),
    orgId: text("org_id").notNull(),
    name: text("name").notNull(),
    // Lowercase hex from TAG_COLORS.
    color: text("color").notNull().default("#6b7280"),
    createdAt: timestamp("created_at", { withTimezone: true })
      .notNull()
      .defaultNow(),
  },
  (table) => [
    uniqueIndex("tags_org_name_unique").on(table.orgId, table.name),
    index("idx_tags_org_id").on(table.orgId),
  ]
)

export const itemTags = pgTable(
  "item_tags",
  {
    // orgId denormalized onto the join row so every query stays org-scoped
    // without an extra join back through items.
    orgId: text("org_id").notNull(),
    itemId: text("item_id").notNull(),
    tagId: text("tag_id").notNull(),
  },
  (table) => [
    primaryKey({ columns: [table.itemId, table.tagId] }),
    index("idx_item_tags_org_id").on(table.orgId),
    index("idx_item_tags_tag_id").on(table.tagId),
  ]
)

/**
 * One batch of fungible (bulk) stock: `qty` units of an item in a single
 * location/status/condition. An item's total quantity is the sum of its
 * batches. Batches auto-delete when they reach qty 0.
 */
export const itemBatches = pgTable(
  "item_batches",
  {
    id: text("id").primaryKey(),
    orgId: text("org_id").notNull(),
    itemId: text("item_id").notNull(),
    qty: integer("qty").notNull(),
    location: text("location").notNull(),
    status: itemStatus("status").notNull().default("In Storage"),
    condition: condition("condition").notNull().default("Good"),
    createdAt: timestamp("created_at", { withTimezone: true })
      .notNull()
      .defaultNow(),
    updatedAt: timestamp("updated_at", { withTimezone: true })
      .notNull()
      .defaultNow(),
  },
  (table) => [
    index("idx_item_batches_org_id").on(table.orgId),
    index("idx_item_batches_item_id").on(table.itemId),
    index("idx_item_batches_location").on(table.location),
    index("idx_item_batches_status").on(table.status),
  ]
)

export const ACTIVITY_ACTIONS = [
  "created",
  "updated",
  "deleted",
  "checked_out",
  "checked_in",
  "reported_damaged",
  "moved",
  "condition_changed",
] as const

export type ActivityAction = (typeof ACTIVITY_ACTIONS)[number]

export const activityAction = pgEnum("activity_action", ACTIVITY_ACTIONS)

export const activityLogs = pgTable(
  "activity_logs",
  {
    id: uuid("id").primaryKey().defaultRandom(),
    orgId: text("org_id").notNull(),
    // No FK so logs survive item deletion. Nullable for the same reason.
    // Stored as text to match items.id (ULID).
    itemId: text("item_id"),
    userId: text("user_id").notNull(),
    userName: text("user_name").notNull().default(""),
    userEmail: text("user_email").notNull().default(""),
    action: activityAction("action").notNull(),
    // Snapshot of the item at the time of the action — keeps the log useful
    // even if the item is later renamed, relocated, or removed.
    itemName: text("item_name").notNull().default(""),
    itemQrCode: text("item_qr_code").notNull().default(""),
    fromLocation: text("from_location"),
    toLocation: text("to_location"),
    fromCondition: condition("from_condition"),
    toCondition: condition("to_condition"),
    // Units affected — set for bulk (batch) actions, null for unit items.
    quantity: integer("quantity"),
    createdAt: timestamp("created_at", { withTimezone: true })
      .notNull()
      .defaultNow(),
  },
  (table) => [
    index("idx_activity_logs_org_id").on(table.orgId, table.createdAt),
    index("idx_activity_logs_item_id").on(table.itemId, table.createdAt),
    index("idx_activity_logs_created_at").on(table.createdAt),
    index("idx_activity_logs_user_id").on(table.userId, table.createdAt),
  ]
)
