packages: []

overrides:
  "@esbuild-kit/core-utils>esbuild": 0.28.2

allowBuilds:
  esbuild: true
  lightningcss: true
  unrs-resolver: true
  msw: false
  sharp: set this to true or false
  workerd: true
  core-js: true
  bufferutil: true
  utf-8-validate: true
