/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as StockRouteImport } from './routes/stock'
import { Route as ScanRouteImport } from './routes/scan'
import { Route as OnboardingRouteImport } from './routes/onboarding'
import { Route as HomeRouteImport } from './routes/home'
import { Route as ActivityRouteImport } from './routes/activity'
import { Route as IndexRouteImport } from './routes/index'
import { Route as StockIndexRouteImport } from './routes/stock/index'
import { Route as ScanIndexRouteImport } from './routes/scan/index'
import { Route as StockNewRouteImport } from './routes/stock/new'
import { Route as SignUpSplatRouteImport } from './routes/sign-up.$'
import { Route as ScanCameraRouteImport } from './routes/scan/camera'
import { Route as ScanBulkRouteImport } from './routes/scan/bulk'
import { Route as LoginSplatRouteImport } from './routes/login.$'
import { Route as StockIdQrRouteImport } from './routes/stock/$id.qr'
import { Route as StockIdHistoryRouteImport } from './routes/stock/$id.history'
import { Route as StockIdEditRouteImport } from './routes/stock/$id.edit'
import { Route as ApiImagesSplatRouteImport } from './routes/api/images/$'

const StockRoute = StockRouteImport.update({
  id: '/stock',
  path: '/stock',
  getParentRoute: () => rootRouteImport,
} as any)
const ScanRoute = ScanRouteImport.update({
  id: '/scan',
  path: '/scan',
  getParentRoute: () => rootRouteImport,
} as any)
const OnboardingRoute = OnboardingRouteImport.update({
  id: '/onboarding',
  path: '/onboarding',
  getParentRoute: () => rootRouteImport,
} as any)
const HomeRoute = HomeRouteImport.update({
  id: '/home',
  path: '/home',
  getParentRoute: () => rootRouteImport,
} as any)
const ActivityRoute = ActivityRouteImport.update({
  id: '/activity',
  path: '/activity',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const StockIndexRoute = StockIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => StockRoute,
} as any)
const ScanIndexRoute = ScanIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => ScanRoute,
} as any)
const StockNewRoute = StockNewRouteImport.update({
  id: '/new',
  path: '/new',
  getParentRoute: () => StockRoute,
} as any)
const SignUpSplatRoute = SignUpSplatRouteImport.update({
  id: '/sign-up/$',
  path: '/sign-up/$',
  getParentRoute: () => rootRouteImport,
} as any)
const ScanCameraRoute = ScanCameraRouteImport.update({
  id: '/camera',
  path: '/camera',
  getParentRoute: () => ScanRoute,
} as any)
const ScanBulkRoute = ScanBulkRouteImport.update({
  id: '/bulk',
  path: '/bulk',
  getParentRoute: () => ScanRoute,
} as any)
const LoginSplatRoute = LoginSplatRouteImport.update({
  id: '/login/$',
  path: '/login/$',
  getParentRoute: () => rootRouteImport,
} as any)
const StockIdQrRoute = StockIdQrRouteImport.update({
  id: '/$id/qr',
  path: '/$id/qr',
  getParentRoute: () => StockRoute,
} as any)
const StockIdHistoryRoute = StockIdHistoryRouteImport.update({
  id: '/$id/history',
  path: '/$id/history',
  getParentRoute: () => StockRoute,
} as any)
const StockIdEditRoute = StockIdEditRouteImport.update({
  id: '/$id/edit',
  path: '/$id/edit',
  getParentRoute: () => StockRoute,
} as any)
const ApiImagesSplatRoute = ApiImagesSplatRouteImport.update({
  id: '/api/images/$',
  path: '/api/images/$',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/activity': typeof ActivityRoute
  '/home': typeof HomeRoute
  '/onboarding': typeof OnboardingRoute
  '/scan': typeof ScanRouteWithChildren
  '/stock': typeof StockRouteWithChildren
  '/login/$': typeof LoginSplatRoute
  '/scan/bulk': typeof ScanBulkRoute
  '/scan/camera': typeof ScanCameraRoute
  '/sign-up/$': typeof SignUpSplatRoute
  '/stock/new': typeof StockNewRoute
  '/scan/': typeof ScanIndexRoute
  '/stock/': typeof StockIndexRoute
  '/api/images/$': typeof ApiImagesSplatRoute
  '/stock/$id/edit': typeof StockIdEditRoute
  '/stock/$id/history': typeof StockIdHistoryRoute
  '/stock/$id/qr': typeof StockIdQrRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/activity': typeof ActivityRoute
  '/home': typeof HomeRoute
  '/onboarding': typeof OnboardingRoute
  '/login/$': typeof LoginSplatRoute
  '/scan/bulk': typeof ScanBulkRoute
  '/scan/camera': typeof ScanCameraRoute
  '/sign-up/$': typeof SignUpSplatRoute
  '/stock/new': typeof StockNewRoute
  '/scan': typeof ScanIndexRoute
  '/stock': typeof StockIndexRoute
  '/api/images/$': typeof ApiImagesSplatRoute
  '/stock/$id/edit': typeof StockIdEditRoute
  '/stock/$id/history': typeof StockIdHistoryRoute
  '/stock/$id/qr': typeof StockIdQrRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/activity': typeof ActivityRoute
  '/home': typeof HomeRoute
  '/onboarding': typeof OnboardingRoute
  '/scan': typeof ScanRouteWithChildren
  '/stock': typeof StockRouteWithChildren
  '/login/$': typeof LoginSplatRoute
  '/scan/bulk': typeof ScanBulkRoute
  '/scan/camera': typeof ScanCameraRoute
  '/sign-up/$': typeof SignUpSplatRoute
  '/stock/new': typeof StockNewRoute
  '/scan/': typeof ScanIndexRoute
  '/stock/': typeof StockIndexRoute
  '/api/images/$': typeof ApiImagesSplatRoute
  '/stock/$id/edit': typeof StockIdEditRoute
  '/stock/$id/history': typeof StockIdHistoryRoute
  '/stock/$id/qr': typeof StockIdQrRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/activity'
    | '/home'
    | '/onboarding'
    | '/scan'
    | '/stock'
    | '/login/$'
    | '/scan/bulk'
    | '/scan/camera'
    | '/sign-up/$'
    | '/stock/new'
    | '/scan/'
    | '/stock/'
    | '/api/images/$'
    | '/stock/$id/edit'
    | '/stock/$id/history'
    | '/stock/$id/qr'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/activity'
    | '/home'
    | '/onboarding'
    | '/login/$'
    | '/scan/bulk'
    | '/scan/camera'
    | '/sign-up/$'
    | '/stock/new'
    | '/scan'
    | '/stock'
    | '/api/images/$'
    | '/stock/$id/edit'
    | '/stock/$id/history'
    | '/stock/$id/qr'
  id:
    | '__root__'
    | '/'
    | '/activity'
    | '/home'
    | '/onboarding'
    | '/scan'
    | '/stock'
    | '/login/$'
    | '/scan/bulk'
    | '/scan/camera'
    | '/sign-up/$'
    | '/stock/new'
    | '/scan/'
    | '/stock/'
    | '/api/images/$'
    | '/stock/$id/edit'
    | '/stock/$id/history'
    | '/stock/$id/qr'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ActivityRoute: typeof ActivityRoute
  HomeRoute: typeof HomeRoute
  OnboardingRoute: typeof OnboardingRoute
  ScanRoute: typeof ScanRouteWithChildren
  StockRoute: typeof StockRouteWithChildren
  LoginSplatRoute: typeof LoginSplatRoute
  SignUpSplatRoute: typeof SignUpSplatRoute
  ApiImagesSplatRoute: typeof ApiImagesSplatRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/stock': {
      id: '/stock'
      path: '/stock'
      fullPath: '/stock'
      preLoaderRoute: typeof StockRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/scan': {
      id: '/scan'
      path: '/scan'
      fullPath: '/scan'
      preLoaderRoute: typeof ScanRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/onboarding': {
      id: '/onboarding'
      path: '/onboarding'
      fullPath: '/onboarding'
      preLoaderRoute: typeof OnboardingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/home': {
      id: '/home'
      path: '/home'
      fullPath: '/home'
      preLoaderRoute: typeof HomeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/activity': {
      id: '/activity'
      path: '/activity'
      fullPath: '/activity'
      preLoaderRoute: typeof ActivityRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/stock/': {
      id: '/stock/'
      path: '/'
      fullPath: '/stock/'
      preLoaderRoute: typeof StockIndexRouteImport
      parentRoute: typeof StockRoute
    }
    '/scan/': {
      id: '/scan/'
      path: '/'
      fullPath: '/scan/'
      preLoaderRoute: typeof ScanIndexRouteImport
      parentRoute: typeof ScanRoute
    }
    '/stock/new': {
      id: '/stock/new'
      path: '/new'
      fullPath: '/stock/new'
      preLoaderRoute: typeof StockNewRouteImport
      parentRoute: typeof StockRoute
    }
    '/sign-up/$': {
      id: '/sign-up/$'
      path: '/sign-up/$'
      fullPath: '/sign-up/$'
      preLoaderRoute: typeof SignUpSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/scan/camera': {
      id: '/scan/camera'
      path: '/camera'
      fullPath: '/scan/camera'
      preLoaderRoute: typeof ScanCameraRouteImport
      parentRoute: typeof ScanRoute
    }
    '/scan/bulk': {
      id: '/scan/bulk'
      path: '/bulk'
      fullPath: '/scan/bulk'
      preLoaderRoute: typeof ScanBulkRouteImport
      parentRoute: typeof ScanRoute
    }
    '/login/$': {
      id: '/login/$'
      path: '/login/$'
      fullPath: '/login/$'
      preLoaderRoute: typeof LoginSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/stock/$id/qr': {
      id: '/stock/$id/qr'
      path: '/$id/qr'
      fullPath: '/stock/$id/qr'
      preLoaderRoute: typeof StockIdQrRouteImport
      parentRoute: typeof StockRoute
    }
    '/stock/$id/history': {
      id: '/stock/$id/history'
      path: '/$id/history'
      fullPath: '/stock/$id/history'
      preLoaderRoute: typeof StockIdHistoryRouteImport
      parentRoute: typeof StockRoute
    }
    '/stock/$id/edit': {
      id: '/stock/$id/edit'
      path: '/$id/edit'
      fullPath: '/stock/$id/edit'
      preLoaderRoute: typeof StockIdEditRouteImport
      parentRoute: typeof StockRoute
    }
    '/api/images/$': {
      id: '/api/images/$'
      path: '/api/images/$'
      fullPath: '/api/images/$'
      preLoaderRoute: typeof ApiImagesSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface ScanRouteChildren {
  ScanBulkRoute: typeof ScanBulkRoute
  ScanCameraRoute: typeof ScanCameraRoute
  ScanIndexRoute: typeof ScanIndexRoute
}

const ScanRouteChildren: ScanRouteChildren = {
  ScanBulkRoute: ScanBulkRoute,
  ScanCameraRoute: ScanCameraRoute,
  ScanIndexRoute: ScanIndexRoute,
}

const ScanRouteWithChildren = ScanRoute._addFileChildren(ScanRouteChildren)

interface StockRouteChildren {
  StockNewRoute: typeof StockNewRoute
  StockIndexRoute: typeof StockIndexRoute
  StockIdEditRoute: typeof StockIdEditRoute
  StockIdHistoryRoute: typeof StockIdHistoryRoute
  StockIdQrRoute: typeof StockIdQrRoute
}

const StockRouteChildren: StockRouteChildren = {
  StockNewRoute: StockNewRoute,
  StockIndexRoute: StockIndexRoute,
  StockIdEditRoute: StockIdEditRoute,
  StockIdHistoryRoute: StockIdHistoryRoute,
  StockIdQrRoute: StockIdQrRoute,
}

const StockRouteWithChildren = StockRoute._addFileChildren(StockRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ActivityRoute: ActivityRoute,
  HomeRoute: HomeRoute,
  OnboardingRoute: OnboardingRoute,
  ScanRoute: ScanRouteWithChildren,
  StockRoute: StockRouteWithChildren,
  LoginSplatRoute: LoginSplatRoute,
  SignUpSplatRoute: SignUpSplatRoute,
  ApiImagesSplatRoute: ApiImagesSplatRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
